### ISSUE TITLE
Command line arguments not working....

### ISSUE THREAD

**Issue by geezer500** [romancin/tinymediamanager-docker#11]
It appears that Command line arguments don't work when called from either the host via the docker "exec" command or directly in a sh console....

https://www.tinymediamanager.org/blog/command-line-arguments/

I want to run tmm overnight without any user interaction...

The CLI commands need bash, which I added via "apk add bash".
They still would not run... :-(  something else needs to be installed...

Would it be possible to upodate the container to allow the CLI to run?

Thanks

**Comment by somedevreally** [comment]
yes need help with command line

**Comment by romancin** [comment]
Fixed on current image, I added support for using tinyMediaManager.sh. Read the README for instructions.
