### ISSUE TITLE
How to send command with script

### ISSUE THREAD

**Issue by joelstitch** [romancin/tinymediamanager-docker#12]
I want to setup my Radarr and TMM together where Radarr find a movie, renames it and sends it to my movies folder and then sends a command to TMM to scan the new files so it download trailers and subtitles. On a windows computer the command would be L:\TinyMediaManager\TinyMediaManagerCMD.exe -updateMovies -scrapeNew

How would I send that command with Docer on a Synology?

**Comment by romancin** [comment]
I will implement this I think it is a good functionality :)

**Comment by romancin** [comment]
Ok, done.

I added the information in the README to use this functionality.
