### ISSUE TITLE
Nothing in Media Folder

### ISSUE THREAD

**Issue by Babynini** [romancin/tinymediamanager-docker#16]
My media files are all located in my QNAP Nas /Multi-player and I have map this address to /media and another address to /config. But when I open the software and add media folder, I cannot see any folder in /Media, also cannot scan anything. But I can see folders in /config.
The strange thing is, if I cut all the media files into QNAP address /Pictures and make new copy of docker, all the files can be seen and scanned. I've tried several folders and /Pictures is the only folder can be scanned. I also tried to create a new folder for media but nothing help. All settings and authority of /Pictures and other address seem to be the same.
Is there any idea to solve the problem?

**Comment by romancin** [comment]
You need to specify the complete path in docker-compose for the volume. In QNAP, all the shares you create are created inside /share directory, so probably in your case you need to specify the volume map as:
 - /share/Multi-player:/media
