### ISSUE TITLE
Possible to have several Media volumes?

### ISSUE THREAD

**Issue by asitemade4u** [romancin/tinymediamanager-docker#19]
Hi,
First, thanks for this excellent port of TMM to Docker! Works very well.
There is just one thing I was wondering about: is it possible to have several Media volumes accessible from within the docker container?
I tried to create symbolic links from the additional volumes to the main one declared in the docker-compose file and it was not recognized.

**Comment by romancin** [comment]
Yes, of course. You only need to map all the volume you need in docker compose, for example:

    volumes:
      - "/share/Peliculas UHD:/media/Peliculas UHD"
      - /share/Peliculas:/media/Peliculas
      - /share/Series:/media/Series

They will be accesible inside TMM container.

**Comment by asitemade4u** [comment]
Thanks !

⁣S.​

**Comment by litris** [comment]
In synology I have changed uid and gid for an admin user and now I can rename what's in / media.

But I can't see a complete folder already created in the root for example volume1 / Movies.

In Docker I add movies pointing to / media

And it doesn't show the content.

I think it does not show contents of a folder purchased at the root of the synology.
