### ISSUE TITLE
scrapper setting : prefered language

### ISSUE THREAD

**Issue by arakeis** [romancin/tinymediamanager-docker#21]
Hi romancin,

And thanks for this great tool which helps a lot

My question : is it possible to specify a prefered language for the scrapping part ?
In my case I have 2 separate directories, one in English, one in French...

Any advise welcome !

thks

**Comment by arakeis** [comment]
after a clean week end, here is the solution I found to be working
I set up 2 container, One with the French settings (media source and language settings), the other one in English.
And the best part is that on my nas (synology) the automation script works fine ! (two scripts obviously).

**Comment by shawnzhou1120** [comment]
hi arakeis
so .what is your automation script?what can the scripts do?

**Comment by arakeis** [comment]
My problem was more a organisational problem than a script one. I had to have 2 different settings, one based on english movies and one in french. The best solution was to duplicate the container,
