### ISSUE TITLE
Updating to V4 causes constant reboots

### ISSUE THREAD

**Issue by ytsejam1138** [romancin/tinymediamanager-docker#45]
I updated to V4 via the app interface and now it just constantly reboots.  Rolling back to V3 fixes the issue.  Please update to work with V4.

Running Docker on a Synology DS918+

**Comment by romancin** [comment]
For the moment I will continue to support v3, as new v4 has implemented a subscription model:

https://www.tinymediamanager.org/purchase/

Maybe I will implement the new version too as a separated branch so anyone can choose the version wanted.

**Comment by jvdivx** [comment]
I am subscribed to version 4, I would be very grateful if you do the docker for it.

Thank you.

**Comment by Xyz00777** [comment]
also subscriber of v4 (because its not so mutch that it would hurt me for that year)
I would really like to see a new branch or new projects (whats easier for you)
are there now (2-3 months later) any plans to start with it?

**Comment by Xyz00777** [comment]
heyho for your information tmm 4 have a new license model.
https://www.tinymediamanager.org/purchase/
you can scrub unlimited episodes movies... like in v3 but you dont have all options like subtitle downloader or traktv sync.
can you please update it now so i can use v4 in container too? propably a new branch so users who want these features but dont want to pay it can use the old version still (if i understood it correct v3 is still not EOL)?

**Comment by romancin** [comment]
Image with TMM v4 is available now. For the moment, both versions will be maintained.
