### ISSUE TITLE
unable to use 3.1.10, always downloading 3.1.6

### ISSUE THREAD

**Issue by ifsnop** [romancin/tinymediamanager-docker#49]
After using 

~~~
docker run -d --name=tinymediamanager \
-v /share/Container/tinymediamanager/config:/config \
-v /share/Container/tinymediamanager/media:/media \
-e GROUP_ID=0 -e USER_ID=0 -e TZ=Europe/Madrid \
-p 5800:5800 \
-p 5900:5900 \
romancin/tinymediamanager:latest
~~~

I'm always getting tmm version 3.1.6. How do I force 3.1.10?

I have deleted all the images from tmm on my system, but suspect that maybe there is some dependency not completed on the docker website. Any help is appreciated!

**Comment by romancin** [comment]
Yes, this application installs also on the persistent directory, so you need to launch also the Update from TMM interface.
