### ISSUE TITLE
(little issue) docker pull is not working becuase of naming

### ISSUE THREAD

**Issue by Xyz00777** [romancin/tinymediamanager-docker#59]
Hi for your information in your readme and in your docker information is standing docker tag v4-lastest but in the docker tags its latest-4 please fix it :)
Greetings
Xyz00777

**Comment by romancin** [comment]
I think it is specified correctly in README:
![CF38F71E-732C-4C07-9C8F-A40DEDC062D5](https://user-images.githubusercontent.com/17579835/113621654-2c572b80-965c-11eb-80b6-5801e8fe0ef9.png)


And the images:
![6D365B56-46EF-47AC-A9CE-D24ABB6B1164](https://user-images.githubusercontent.com/17579835/113621594-18132e80-965c-11eb-833a-f196e7e472db.png)

**Comment by Xyz00777** [comment]
Okay in the first picture its correct. But in the sample docker command its incorrect
There stand xxxx/tinymediamanager:v4-latest
I didnt see it that its correct in the table
