### ISSUE TITLE
Fresh install is broken

### ISSUE THREAD

**Issue by mplorentz** [romancin/tinymediamanager-docker#6]
When I start up the docker container for the first time I get an error in `/config/logs/output.log` that `getdown.jar` cannot be found. Looks like the 2.9.17.1 version of tinyMediaManager has changed the location of its files from previous version.

**Comment by romancin** [comment]
Thank you for advise. Could you please test with the current image? Thank you!

**Comment by mplorentz** [comment]
It works now! Thanks for fixing it.
