### ISSUE TITLE
Black Screen when launching TMM after upgrading to v4

### ISSUE THREAD

**Issue by ejkeebler** [romancin/tinymediamanager-docker#61]
I can launch the included v3 and even update to v3.14? but as soon as I update to v4, I just get a black screen.  I'm sure this is related to x somehow.  I do install this on a vm with know x windows, but v3 seemed to work ok.

30/04/2021 09:55:03 GrabServer control via XTEST.

30/04/2021 09:55:03 

30/04/2021 09:55:03 Scroll Detection: -scrollcopyrect mode is in effect to

30/04/2021 09:55:03   use RECORD extension to try to detect scrolling windows

30/04/2021 09:55:03   (induced by either user keystroke or mouse input).

30/04/2021 09:55:03   If this yields undesired behavior (poor response, painting

30/04/2021 09:55:03   errors, etc) it may be disabled via: '-noscr'

30/04/2021 09:55:03   Also see the -help entry for tuning parameters.

30/04/2021 09:55:03   You can press 3 Alt_L's (Left "Alt" key) in a row to 

30/04/2021 09:55:03   repaint the screen, also see the -fixscreen option for

30/04/2021 09:55:03   periodic repaints.

30/04/2021 09:55:03 

30/04/2021 09:55:03 XKEYBOARD: number of keysyms per keycode 7 is greater

30/04/2021 09:55:03   than 4 and 51 keysyms are mapped above 4.

30/04/2021 09:55:03   Automatically switching to -xkb mode.

30/04/2021 09:55:03   If this makes the key mapping worse you can

30/04/2021 09:55:03   disable it with the "-noxkb" option.

30/04/2021 09:55:03   Also, remember "-remap DEAD" for accenting characters.

30/04/2021 09:55:03 

30/04/2021 09:55:03 X FBPM extension not supported.

Xlib:  extension "DPMS" missing on display ":0".

30/04/2021 09:55:03 X display is not capable of DPMS.

30/04/2021 09:55:03 --------------------------------------------------------

30/04/2021 09:55:03 

30/04/2021 09:55:03 Default visual ID: 0x21

30/04/2021 09:55:03 Read initial data from X display into framebuffer.

30/04/2021 09:55:03 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120

30/04/2021 09:55:03 

30/04/2021 09:55:03 X display :0 is 32bpp depth=24 true color

30/04/2021 09:55:03 

30/04/2021 09:55:03 Listening for VNC connections on TCP port 5900

30/04/2021 09:55:03 Listening for VNC connections on TCP6 port 5900

30/04/2021 09:55:03 listen6: bind: Address in use

30/04/2021 09:55:03 Not listening on IPv6 interface.

30/04/2021 09:55:03 

30/04/2021 09:55:03 Xinerama is present and active (e.g. multi-head).

30/04/2021 09:55:03 Xinerama: number of sub-screens: 1

30/04/2021 09:55:03 Xinerama: no blackouts needed (only one sub-screen)

30/04/2021 09:55:03 

30/04/2021 09:55:03 fb read rate: 439 MB/sec

30/04/2021 09:55:03 fast read: reset -wait  ms to: 10

30/04/2021 09:55:03 fast read: reset -defer ms to: 10

30/04/2021 09:55:03 The X server says there are 10 mouse buttons.

30/04/2021 09:55:03 screen setup finished.

30/04/2021 09:55:03 

The VNC desktop is:      docker:0
      

0

******************************************************************************

Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster

retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.

More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

30/04/2021 09:55:05 Got connection from client 127.0.0.1

30/04/2021 09:55:05   other clients:

30/04/2021 09:55:05 Got 'ws' WebSockets handshake

30/04/2021 09:55:05 Got protocol: binary

30/04/2021 09:55:05   - webSocketsHandshake: using binary/raw encoding

30/04/2021 09:55:05   - WebSockets client version hybi-13

30/04/2021 09:55:05 Disabled X server key autorepeat.

30/04/2021 09:55:05   to force back on run: 'xset r on' (3 times)

30/04/2021 09:55:05 incr accepted_client=1 for 127.0.0.1:47922  sock=11

30/04/2021 09:55:05 Client Protocol Version 3.8

30/04/2021 09:55:05 Protocol version sent 3.8, using 3.8

30/04/2021 09:55:05 rfbProcessClientSecurityType: executing handler for type 1

30/04/2021 09:55:05 rfbProcessClientSecurityType: returning securityResult for client rfb version >= 3.8

30/04/2021 09:55:05 Pixel format for client 127.0.0.1:

30/04/2021 09:55:05   32 bpp, depth 24, little endian

30/04/2021 09:55:05   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0

30/04/2021 09:55:05 no translation needed

30/04/2021 09:55:05 Enabling NewFBSize protocol extension for client 127.0.0.1

30/04/2021 09:55:05 Enabling full-color cursor updates for client 127.0.0.1

30/04/2021 09:55:05 Using image quality level 6 for client 127.0.0.1

30/04/2021 09:55:05 Using JPEG subsampling 0, Q79 for client 127.0.0.1

30/04/2021 09:55:05 Using compression level 9 for client 127.0.0.1

30/04/2021 09:55:05 Enabling LastRect protocol extension for client 127.0.0.1

30/04/2021 09:55:05 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)

30/04/2021 09:55:05 Using tight encoding for client 127.0.0.1

[services.d] starting logmonitor...

[services.d] starting app...

[logmonitor] no file to monitor: disabling service...

[app] starting TinyMediaManager...

[services.d] done.

[tmmsupervisor] TinyMediaManager not started yet.  Proceeding...

30/04/2021 09:55:06 client_set_net: 127.0.0.1  0.0001

30/04/2021 09:55:06 created   xdamage object: 0x20002c

30/04/2021 09:55:07 copy_tiles: allocating first_line at size 41

30/04/2021 09:55:07 client 1 network rate 246.4 KB/sec (16758.2 eff KB/sec)

30/04/2021 09:55:07 client 1 latency:  2.7 ms

30/04/2021 09:55:07 dt1: 0.0109, dt2: 0.0339 dt3: 0.0027 bytes: 10730

30/04/2021 09:55:07 link_rate: LR_UNKNOWN - 2 ms, 246 KB/s

30/04/2021 09:55:15 created selwin: 0x20002d

30/04/2021 09:55:15 called initialize_xfixes()

**Comment by ejkeebler** [comment]
ok, using the tag latest-v4 fixes this issue.  Rather than upgrading! the github docker compose example, uses v4-latest, which can't be used.

**Comment by sheep94lion** [comment]
I delete all existing files in config directory and rerun it. It works fine now.
