### ISSUE TITLE
not working anymore with newest tmm version

### ISSUE THREAD

**Issue by Xyz00777** [romancin/tinymediamanager-docker#66]
Hello,
I updated from 4.2.3 to the newest version of tinymediamanager 4.2.4 a moment ago and the container dont start anymore... please help (edit: i got it reversed to the old version and can use it again, but updating does not work anymore, until 4.2.3 it worked without problems) please fix.
Greetings

**Comment by ileodo** [comment]
observed the same issue.

**Comment by Xyz00777** [comment]
@ileodo FYI I think it will not get developed anymore because there is now a official docker image

**Comment by ileodo** [comment]
well, the official one is using noVNC, which display the UI in a super strange way..
as of now, I think this docker still works better.

**Comment by romancin** [comment]
Sorry for being so late. This image is still being developed. It is awesome that now there is an official one, but for the moment it makes sense to me to maintain this one. The image is now updated to latest version:
https://github.com/romancin/tinymediamanager4-docker/pull/14/files
