### ISSUE TITLE
Slow renaming speed

### ISSUE THREAD

**Issue by tulkarxxx** [romancin/tinymediamanager-docker#67]
Hi, 
I don,t know if is configuration issue or a bug, when renaming movies  over a  rclone mounted drive, renaming speed is exactly one file per minute.
In a big library this is a big issue 

Best regards

**Comment by romancin** [comment]
Sorry, but using TMM over rclone and having performance issues with it is outside the purpose of this image. Can you reproduce the problem if you use TMM outside docker?

**Comment by tulkarxxx** [comment]
Same issue even not using docker, has to be something related with mounted drive
Close the issue and sorry for inconveniences
