### ISSUE TITLE
font WenQuanYi Zen Hei can not be installed

### ISSUE THREAD

**Issue by qwinwin** [romancin/tinymediamanager-docker#72]
docker image: latest-V4

error msg:
> fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
> ERROR: FDB format error (line 42670)

seems someting wrong with apk-tools(2.10.8-r0) and it need upgrading to version(2.10.8-r1) to solve this issue(see below)

> Upgrading apk-tools (2.10.8-r0 -> 2.10.8-r1)
> add-pkg wqy-zenhei --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
> fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz

**Comment by SilenceEagle** [comment]
Similar issue on v3:
>[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: installing CJK font...
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz: UNTRUSTED signature
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
[cont-init.d] 10-cjk-font.sh: ERROR: unsatisfiable constraints:
[cont-init.d] 10-cjk-font.sh:   wqy-zenhei (missing):
[cont-init.d] 10-cjk-font.sh:     required by: world[wqy-zenhei]
[cont-init.d] 10-cjk-font.sh: exited 0.

My device: `Qnap TS-453Dmini` NAS, this error will occur when install it from `Container Station` and set `ENABLE_CJK_FONT` to 1.

Any advice? Tks!

**Comment by imnpc** [comment]
`
wget https://mirrors.aliyun.com/alpine/edge/testing/x86_64/font-wqy-zenhei-0.9.45-r2.apk
apk add --allow-untrusted font-wqy-zenhei-0.9.45-r2.apk
`

**Comment by qwinwin** [comment]
> ```shell
> wget https://mirrors.aliyun.com/alpine/edge/testing/x86_64/font-wqy-zenhei-0.9.45-r2.apk
> 
> apk add --allow-untrusted font-wqy-zenhei-0.9.45-r2.apk
> ```

阿里云镜像有的地方会很慢 可以换ustc的

`wget https://mirrors.ustc.edu.cn/alpine/edge/testing/x86_64/font-wqy-zenhei-0.9.45-r2.apk && apk add --allow-untrusted font-wqy-zenhei-0.9.45-r2.apk`

**Comment by con2000us** [comment]
> ```shell
> wget https://mirrors.aliyun.com/alpine/edge/testing/x86_64/font-wqy-zenhei-0.9.45-r2.apk
> 
> apk add --allow-untrusted font-wqy-zenhei-0.9.45-r2.apk
> ```

版本改了 使用下面

wget https://mirrors.aliyun.com/alpine/edge/testing/x86_64/font-wqy-zenhei-0.9.45-r3.apk

apk add --allow-untrusted font-wqy-zenhei-0.9.45-r3.apk

**Comment by luckkyboy** [comment]
The latest as follows:

https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/font-wqy-zenhei-0.9.45-r3.apk
OR
https://mirrors.aliyun.com/alpine/edge/community/x86_64/font-wqy-zenhei-0.9.45-r3.apk

**Comment by chrovex** [comment]
> ```shell
> wget https://mirrors.aliyun.com/alpine/edge/testing/x86_64/font-wqy-zenhei-0.9.45-r2.apk
> 
> apk add --allow-untrusted font-wqy-zenhei-0.9.45-r2.apk
> ```

Should switch to other alpine mirrors to avoid being stuck in "fetch APKINDEX.tar.gz" issue when using 'apk add', even if you have downloaded the package locally. The whole code look like this:
```shell
sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

wget https://mirrors.tuna.tsinghua.edu.cn/alpine/edge/community/x86_64/font-wqy-zenhei-0.9.45-r3.apk

apk add --allow-untrusted font-wqy-zenhei-0.9.45-r3.apk

rm font-wqy-zenhei-0.9.45-r3.apk
``` 
This should work on other docker images based on alpine which have 'xx-cjk-font.sh'

**Comment by xmlys15** [comment]
```
sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories

wget https://mirrors.tuna.tsinghua.edu.cn/alpine/edge/community/x86_64/font-wqy-zenhei-0.9.45-r4.apk

apk add --allow-untrusted font-wqy-zenhei-0.9.45-r4.apk

rm font-wqy-zenhei-0.9.45-r4.apk
```
