### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by TonBon** [romancin/tinymediamanager-docker#9]
I'm sorry I open an issue for it, I don't see any other way of posting a thank you; thank you very much!

I installed on Synology DSM 6.2, it works perfectly; thank you!

One suggestion: the command has:

`-v /share/Container/tinymediamanager/config:/config \
-v /share/Container/tinymediamanager/media:/media \`

As I am a noob on Docker I pasted that in the CLI: it gave an error:

`docker: Error response from daemon: Bind mount failed: '/share/Container/tinymediamanager/media' does not exists.`

Via the Docker GUI in DSM I tried /volume1/docker/tinymediamanager/config and /volume1/docker/tinymediamanager/media and it started.

Perhaps you could add this to the instructions.

**EDIT**: I do have a question: how do I add movies and TV-shows to TMM? It doesn't show /volume1/ when I browse for media?

**EDIT: ANSWER**: the /media switch in volumes is for that I discovered.

**EDIT: NEW QUESTION:** is there a way to make the screen more readable? Like maximized? Because currently it is not readable and see now way to expand the screen size to my native desktop full screen:

https://ibb.co/4RQmQgb

Thank you again!

Bye,

**Comment by TonBon** [comment]
It seems there is a memory problem:

https://ibb.co/DW3Rmny

It doesn't take nearly as much RAM on Windows 7 (780 MB).

**Comment by romancin** [comment]
With the first problem, the directory before ":" must be a directory in your host that should exist, you need to adapt it to your own case as you have done :)

With the last question, use the vertical line made of points to adjust it:
![image](https://user-images.githubusercontent.com/17579835/64564869-cf49a580-d352-11e9-8d8c-a9fdf7b2d43f.png)

I think more resolution would be too much, but I understand this is personal thoughts.

About RAM, no problem here on QNAP, so maybe it's Synology Docker version who is causing it (this container is not too much heavy, son that numbers are completely abnormal:

![image](https://user-images.githubusercontent.com/17579835/64564638-492d5f00-d352-11e9-9add-7704782b0bf8.png)

**Comment by TonBon** [comment]
Thank you for your answer. Your screenshot seems very usable, but my screen is not.

Could I ask: what do you mean with "use the vertical line made of points to adjust it"?

I don't see any vertical line consisting of points? The line right to the right of the movie title is non-draggable for me.

I use Chrome on Windows 7, what do you use?

Thank you again!

**Comment by romancin** [comment]
I use Chrome on macOS.

Don't you see this in the middle of the vertical line?

**Comment by TonBon** [comment]
Thank you for your answer, and I apologize for being stupid, I was looking to the utmost left of the screen :-)

Docker is a learning process for me, and even though the instructions you wrote, a mule like me overlooks them. Because screen parameters appear to be able to be set in the environmental parameters:


DISPLAY_WIDTH | Width (in pixels) of the application's window. | 1280
DISPLAY_HEIGHT | Height (in pixels) of the application's window. | 768

I changed it to 1920 and 1080, and it seems better readable; thank you again :dancing_men: 

Could I ask: what does DISPLAY=:0 do in the settings?

Kind regards,

**Comment by romancin** [comment]
Awesome you are learning so fast! An advice to you: the container world creates addiction :P

That option indicates VNC to Connect to the Active display, that is where tmm is running. VNC is used to Connect to the Desktop from the web application.

**Comment by litris** [comment]
> I'm sorry I open an issue for it, I don't see any other way of posting a thank you; thank you very much!
> 
> I installed on Synology DSM 6.2, it works perfectly; thank you!
> 
> One suggestion: the command has:
> 
> `-v /share/Container/tinymediamanager/config:/config \ -v /share/Container/tinymediamanager/media:/media \`
> 
> As I am a noob on Docker I pasted that in the CLI: it gave an error:
> 
> `docker: Error response from daemon: Bind mount failed: '/share/Container/tinymediamanager/media' does not exists.`
> 
> Via the Docker GUI in DSM I tried /volume1/docker/tinymediamanager/config and /volume1/docker/tinymediamanager/media and it started.
> 
> Perhaps you could add this to the instructions.
> 
> **EDIT**: I do have a question: how do I add movies and TV-shows to TMM? It doesn't show /volume1/ when I browse for media?
> 
> **EDIT: ANSWER**: the /media switch in volumes is for that I discovered.
> 
> **EDIT: NEW QUESTION:** is there a way to make the screen more readable? Like maximized? Because currently it is not readable and see now way to expand the screen size to my native desktop full screen:
> 
> https://ibb.co/4RQmQgb
> 
> Thank you again!
> 
> Bye,

How did you add folders with your library from Docker on Synology? 

Don't you have problems with permissions?

Depending on how I copy and stick the film in the folder I can or can't rename.
